### ISSUE TITLE
Build background database for structural variants

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#32]
**Is your feature request related to a problem? Please describe.**
Currently we are limited to SV counts as computed before the import.

**Describe the solution you'd like**
Implement building a summary background database for this similar to how it's done for the small variants.

**Describe alternatives you've considered**
N/A

**Additional context**
- #566

**Comment by holtgrewe** [comment]
**Implementation Proposal**
1. Introduce a new background data table that corresponds to the `variants.models.SmallVariantSummary`.
   We most likely will need a number of supporting tables for implementing rebuilding in the background.
2. Extend the SV queries to join this table as it would join to gnomAD-SV etc.
3. Display the result just as it would be done for gnomAD-SV overlaps.
4. Deprecate the support for the cohort-wide count information from import from VCF.
   A ticket should be added to remove this.

**Affected Components**
- VarFish Server.

**Affected Modules/Files**
- `svs.*` potentially all Python modules and templates

**Required Architectural Changes**
Currently, we rely on the annotation of background counts from external databases. This additional dependency is removed. There is no large-scale architectural change.

**Required Database Model Changes**
We need to introduce new models in the `svs.models` module.

- `svs.models.BackgroundSvSet`
- `svs.models.BackgroundSv`

**Implementation Sketch**
We can extend the query infrastructure accodring to the existing implementation. The same is true for the display of overlaps. In the long run, the information from the INFO tags should not be used any more (an extra ticket will be created). The main task is a proper implementation of building the SV background dataset.

*Storing background SVs*

We can do this in a straightforward fashion and use the same structure as, e.g., we use for gnomAD-SV. We should store separate counts for index and non-index carriers. We can assume all indices are unrelated.

Storing the linear structural variants, DEL, DUP, INV, INS is straightforward as we can represent them with `(svtype, chrom, pos, end)` and cluster them by this information and allowing some "slack" on the positions. Storing break-ends (BNDs) is more tricky because of their non-linear structure. Tools will in general only create one break-end entry and we need to expand this into two (from both sides). Care must be taken to store the strandness/direction of the variant.

We should most likely generalize this and store for each SV in the background database: `(svtype, chrom, pos, end, strand, chrom2, pos2, end2, strand2)`.

*Storing background SV sets*

Building the background sets might take some time. We should thus introduce another model that stores one background SV set with a `state` field that indicates whether the background SV set is currently being built. When performing SV queries, we first pull all existing SVs sets from the database and take the most recent active ones. Only SVs from that set are used for annotation.

*Background SV set life cycle / tasks*

We need background celery tasks for building a new background SV set and for removing old ones. We should also provide Django management commands for launching the creation and cleanup.

*Building background SVs*

First of all, a new background sv set is created with state "building".

Second, the following is done for each chromosome and each variant type.

- load all variants of the given type from each variant
- use [NCLS](https://github.com/biocore-ntnu/ncls) for fast overlap queries and create SV clusters, see below
- insert new clusters with counts into background sv set

Third, the background sv set gets its state updated to "active", all others are marked as "inactive".

*SV Clustering*

Use the following algorithm to determine an initial set of clusters. The steps are executed for each SV of the current chromosome in random order:

- find best matching cluster by Jaccard index, require 0.75 reciprocal overlap and assign SV to it
- if no SV could be found then create a new cluster
- each cluster has a pairwise Jaccard similarity matrix that is updated when new SVs are added, one with minimal median distance to other intervals is taken as the cluster representative
- once a cluster reaches a size of 500 SVs, we randomly subsample 100 SVs and use it as the new cluster

We most likely want to think about this algorithm at a later point.

**Implementation Steps**
- [ ] models
    - [ ] `svs.models.BackgroundSvSet`
    - [ ] `svs.models.BackgroundSv`
- [ ] background jobs
    - [ ] `svs.tasks.create_background_sv_set`
    - [ ] `svs.tasks.cleanup_background_sv_sets`
- [ ] query infrastructure
    - [ ] `svs.queries`
- [ ] SV clustering
