### ISSUE TITLE
Provide easy access to find other carriers of a variant

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#470]
**Is your feature request related to a problem? Please describe.**
The in-house database is useful for excluding artifacts. Sometimes it would be very helpful to identify the carriers (if one has access to it).

**Describe the solution you'd like**
Provide a "view all carriers of this variant" functionality.

**Describe alternatives you've considered**
N/A

**Additional context**
This could also be expanded to a "show everything (rare) in this gene" functionality.

**Comment by holtgrewe** [comment]
**Implementation Proposal**
- Provide a button with `mdi:binoculars` that opens a modal.
- This modal loads a server-rendered page that displays the cases that this variant has also been located in if the user has access to it.
- If the access is restricted it will display the owner of the project that has this data.
- A global configuration setting `VARFISH_RESTRICT_CARRIER_LOOKUP` (default is `0`/`False`) allows to disable the display of restricted access. This is required for `varfish-demo`.

**Affected Components**
VarFish Demo

**Affected Modules/Files**
```
variants/templates/...
variants/views.py
variants/urls.py
```

**Required Architectural Changes**
None

**Required Database Changes**
None

**Is Backport Possible**
Yes

**Implementation Steps**
1. Implement "view variant in other carriers" view
    - [ ] Create a new view for this named `VariantInContextView`. This is also the place to later on plot more information such as "all variants in this gene"
    - [ ] Hook the view to the URLs
    - [ ] Create appropriate template for this
    - [ ] Integrate it into the front-end to display as a modal
    - [ ] Write tests
2. Extend to display some more information
    - [ ] consider using [lollipops](https://github.com/joiningdata/lollipops) for display of other variants in VarFish
    - [ ] possibly allow display of gnomAD data there as well
