### ISSUE TITLE
Create a pull request template with checklist

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#612]
**Is your feature request related to a problem? Please describe.**
We previously had a pull request that had a too simple comment in the commit. Something like this cannot be enforced automatically. We need a template that provides check lists for both the creator of a pull request and the 

**Describe the solution you'd like**
- [ ] if necessary, rework the VarFish developer documentation to describe the processes and requirements better
- [ ] add a pull request template containing at least the information below
- [ ] add a note of this to the VarFish developer documentation

Initial template proposal (inspired by template from [BioConda](https://github.com/bioconda/bioconda-recipes/blob/master/.github/PULL_REQUEST_TEMPLATE.md))

~~~markdown
<!--
Thank you for contributing to VarFish!

Please ensure that you have read the VarFish developer documentation and understand the
processes for contributing to VarFish:

- **Link to Development Overview**
- **Link to Process Description**
- **Links to Checklists and Templates**

In case of any questions, please reach out to the developers by sending an email to
varfish-developers@charite.de
-->

<PLACEHOLDER: Replace this line with a description of your PR>

**Additional Info**

- backport intended: <YES/NO/REMOVE LINE>
- is backport of: #<PR/NUMBER/REMOVE LINE>

**Pull Request Checklist**

My pull request...

- [ ] is referring to an an issue and mentions it in the first line of the message
- [ ] contains a single or semantically separated patches in a linear history
- [ ] consists of patches with terse yet meaningful messages with the required trailers

Reviewers should use the following template in their review.

<details>
  <summary>Click to see reviewer checklist template</summary>

```markdown
The following points will be checked before starting the actual review process and double-checked before accepting the merge request.

**Pre-Review Checklist**

- [ ] pull request title and description comply with requirements
- [ ] patches' history comply as linear and sane semantic units
- [ ] patches' messages comply, in particular first message lines
```
</details>

~~~

**Describe alternatives you've considered**
N/A

**Additional context**
- [GitHub Docs: Creating a pull request template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
