### ISSUE TITLE
Import of "case-spanning" user variant annotation

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#747]
**Is your feature request related to a problem? Please describe.**
While it is possible to perform a case-specific annotation of variants, it is not possible to annotate variants independent of cases. Users with other "legacy" software cannot easily import their previous annotations that might not be case-specific (e.g., JSI SeqPilot).

**Describe the solution you'd like**
Create a new module that allows users to create "custom annotation sets" and and "custom annotation records". These sets should be stored in projects. Users should be able to use the sets available to them for annotation.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by your-highness** [comment]
Thanks @holtgrewe !

A module for the import of Custom Annotation DBs, _e.g. in house_ variant database, allows for a seemless transition from any software to VarFish. This feature and a in depth documentation is highly encouraged.

I think the best approach would be to use TAB-delimited genome position files with preceding variable value columns (see http://www.htslib.org/doc/tabix.html ) which should be defined through a manifest file.

Questions:
1. _I assume the imported values can not be edited within VarFish?_
2. _Is backport to athenea possible?_

**Comment by holtgrewe** [comment]
**Resolution Proposal**
Create a new `varannos` app that allows to manage `VariantCommentSet` objects that carry `VariantComment` records. Each `VariantCommentSet` will live in a project and thus use the same access control. Each such set has a fixed genome build/release. Users can define custom columns for each set (stored as PostgreSQL arrays of strings). Users can then create `VariantComment` entries with genomic coordinates (`release`, `chromosome`, `start`, `end`, `reference`, `alternative`), `date_created`, `date_modified`, and a `data` column. The `data` column is a JSON field that allows to store values for each of the `VariantCommentSet` columns.

For a first version, it is sufficient to provide a REST API to manage the data sets.

The number of possible annotation of variants is starting to be big. We should not hard-code the support for `varannos` into `variants` but rather provide a plugin point in the `variants` app for this. This will serve as a role model for further plugin points (e.g., gene panel providers, phenotype similarity score provider, etc.).

**Affected Components**
VarFish Server

**Affected Modules/Files**
- `variants`, in particular the result display and query infrastructure
- new module `varannos`

**Required Architectural Changes**
Addition of plugin point that will serve as a role model for further plugin points.

**Required Database Changes**
New module `varannos`, nothing in the current code.

**Backport Possible?**
Yes

**Work Plan**
- [ ] implement the models and REST API of `varannos`
- [ ] define plugin point in `variants`
- [ ] integrate with `variants`
- [ ] complete tests
- [ ] create follow-up ticket that specifies a UI
- [ ] create follow-up ticket for integration with Vue.js based filtration

**Comment by holtgrewe** [comment]
@your-highness created specification for new feature, this should answer your questions

**Comment by your-highness** [comment]
Looking great. I support the idea of using a variants plugin for custom annotations.

_Does this feature also address the import of pre-existing user annotations into the database?_

_Any timeframe for this?_

**Comment by holtgrewe** [comment]
@your-highness well, there will be a REST API, around which users can forge their own client and contribute to `varfish-cli` ;-).

**Comment by holtgrewe** [comment]
`varfish-cli` v0.4.0 provides CRUD client functionality. I suggest to implement a higher-level IMPORT variant that defines the variant annotation set as YAML and the variant annotations from TSV.
