### ISSUE TITLE
Allow to ingest clinvar submission report from ClinVar

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#759]
**Is your feature request related to a problem? Please describe.**
ClinVar sends a respose "report" for variant submissions that also contains the clinvar ID of submissions. We do not have a way to read this back into VarFish `clinvar_export`.

**Describe the solution you'd like**
Implement ingestion of ClinVar report.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by holtgrewe** [comment]
**Resolution Proposal**
Allow users to provide a URL with the report (from the URL) to the clinvar submission set. The TSV should be downloaded, stored, and processed. For each row, attach the information to each variant. The same is true for error reports.

We should make the two assumptions that (1) we will only have one report for each submission, at least for each entry, or can overwrite in case of error reports, and (2) the return values from the API might actually change so we want to store the results as JSON.

**Affected Components**
VarFish Server

**Affected Modules/Files**
`clinvar_export`

**Required Architectural Changes**
None

**Required Database Changes**
We need two new nullable JSON fields on the `Submission` model:

- `clinvar_submitter_report`
- `clinvar_error_support`

We should add a new model `ClinVarReport` with the fields

- sodar_uuid
- date_created
- date_modified
- source_url
- contents_md5
- contents

**Backport Possible?**
Yes

**Implementation Plan**
- [ ] extend / create models, add tests, add factories
- [ ] add AJAX API endpoint to `clinvar_export` with tests to fetch from clinvar, timeout is 2s
    - [ ] fetch from clinvar and store in ClinVarReport
    - [ ] parse report contents and store in submission
- [ ] add AJAX API endpoint to fetch local report contents
- [ ] extend serializers of submissions
- [ ] extend Vue.js app to display the result

**Appendix: Report Example**

```
##ClinVar report of published submitted records (SCVs) in SUB12094079
##Organization: Institute for Medical Genetics and Human Genetics, Charité - Universitätsmedizin Berlin
##Date: 2022-09-24
##Explanation of the columns in this report
#Your_variant_id                                    The local ID you may have submitted for the reported allele. May be null.
#VariationID                                        ClinVar's Variation ID (see https://www.ncbi.nlm.nih.gov/clinvar/docs/identifiers/#ids). This is the identifier used to build the URL to the variation page, e.g. https://ncbi.nlm.nih.gov/clinvar/variation/9
#AlleleID                                           ClinVar's Allele ID (see https://www.ncbi.nlm.nih.gov/clinvar/docs/identifiers/#ids). SCVs for a haplotype or genotype have a list of Allele IDs.
#Your_record_id                                     The linking ID/local key you may have submitted for the variant-condition pair. May be null.
#SCV                                                The accession number assigned by ClinVar to your submitted interpretation of the variant-condition pair.
#RCV                                                The accession assigned by ClinVar to the aggregation of your submitted record with other submitted records for the same variant-condition pair.
#Your_variant_description_HGVS                      The HGVS description you provided for the variant in this record. This column may be null if you submitted chromosome coordinates instead of HGVS.  SCVs for a haplotype or genotype have a concatenated list of variant descriptions.
#Your_variant_description_chromosome_coordinates    The chromosome coordinates description you provided for the variant in this record. This column may be null if you submitted HGVS instead of chromosome coordinates.  SCVs for a haplotype or genotype have a concatenated list of variant descriptions. Cytogenetic descriptions are also reported in this column.
#Preferred_variant_name                             The preferred name that ClinVar calculated for the Variation ID. This name is shown on the ClinVar web site in search results and as the title on the variation page.
#Your_condition_name                                The name you submitted for the interpreted condition. May be null if you submitted a database identifier instead.
#Your_condition_identifier                          The database identifier you submitted for the interpreted condition. May be null if you submitted a name instead.
#ClinVar_condition_name                             The preferred condition name in ClinVar.
#Assigned_Concept_ID                                The MedGen Concept ID (CUI) for the preferred condition name in ClinVar. May be null.
#Clinical_significance                              Your submitted interpretation for the variation-condition pair.
#Date_last_evaluated                                Your report of the last date you evaluated the variation-condition pair. May be null.
#Assertion_criteria                                 The name of the assertion criteria you provided for this record. May be null.
#Submission_date                                    The date of your latest published submission for this record.
#Submitted_gene                                     The gene symbol you provided for the submitted variant. May be null.
#Novelty                                            The contribution your initial submission made relative to other records in ClinVar. (new allele|existing allele; new phenotype for this allele|existing combination of allele and phenotype)
#Status                                             The status of the SCV being reported. (current, delete, secondary)
#Info                                               Information about this record relative to other data at NCBI. They are not considered errors; they indicate data that you may want to review. May be null.
#Your_variant_id        VariationID     AlleleID        Your_record_id  SCV     RCV     Your_variant_description_HGVS   Your_variant_description_chromosome_coordinates Preferred_variant_name  Your_condition_name     Your_condition_identifier       ClinVar_condition_nameAssigned_Concept_ID      Clinical_significance   Date_last_evaluated     Assertion_criteria      Submission_date Submitted_gene  Novelty Status  Info
        1308964 1300992 be23703f-fd0c-40ed-82c2-f9e22f9b63f0    SCV002574869                    <SequenceLocation Assembly="GRCh37" Chr="X" start="53265558" stop="53265558" referenceAllele="C" alternateAllele="T"/>  NM_001111125.3(IQSEC2):c.3397G>A (p.Asp1133Asn)       OMIM:309530      Intellectual disability, X-linked 1     C2931498        Uncertain significance  Sep 22, 2022    ACMG Guidelines, 2015   Sep 23, 2022    IQSEC2  existing allele; new phenotype  current
        1706552 1704862 48a2619a-2796-4bf9-9bee-cff4c8027d2f    SCV002574870                    <SequenceLocation Assembly="GRCh37" Chr="X" start="13738101" stop="13738101" referenceAllele="C" alternateAllele="A"/>  NM_001011658.4(TRAPPC2):c.-19G>T                OMIM:313400    Spondyloepiphyseal dysplasia tarda, X-linked    C3541456        Uncertain significance  Sep 22, 2022    ACMG Guidelines, 2015   Sep 23, 2022    TRAPPC2 new allele      current
```
