### ISSUE TITLE
Implement SV filtration with Vue.js

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#775]
**Is your feature request related to a problem? Please describe.**
The SV filtration is still based on the old HTML+JQuery stack.

**Describe the solution you'd like**
We need to convert this as Vue.js.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by holtgrewe** [comment]
**Resolution Proposal**
We will need to add a new background job for the filtration and the necessary infrastructure for storing queries and their results for SVs. We further need to reimplement the SV filtration in Vue.js

**Affected Components**
VarFish server

**Affected Modules/Files**
- `svs`
- `varfish/vueapp`

**Required Architectural Changes**
- Adding new `svs/vueapp`

**Required Database Changes**
- Introduce `BackgroundJob` for SV filtration as well as `SvQuery` and supporting models (see below).

**Backport Possible?**
No

**Implementation Plan**
- [ ] Django Backend
    - [ ] `svs.query_schemas` - new module with the query schema with attrs-based models for the SV filtration, model after small variant filtration
    - [ ] `svs.query_presets` - new module with models and values for the SV query presets, model after small variant implementation
    - [ ] `svs.models`
        - [ ] Add a new `SvQuery` model for storing query settings
        - [ ] Add a new `SvQueryResults` model for storing query results
        - [ ] Add a new `FilterBgJob` for keeping track of the SV filtration job
        - [ ] Add implementation of `FilterBgJob` for SVs
    - [ ] `svs.tasks`
        - [ ] Add task for running the SV query, calls implementation in `svs.models`
    - [ ] `svs.api` (mirrored in `svs.ajax`)
        - [ ] SvQueryListApiView
        - [ ] SvQueryCreateApiView
        - [ ] SvQueryRetrieveApiView
        - [ ] SvQueryUpdateApiView
        - [ ] SvQueryDestroyApiView
        - [ ] SvQueryResultsRetrieveApiView
        - [ ] SvQueryDetailsApiView
        - [ ] SvQuerySettingsShortcutApiView
        - [ ] SvQueryQuickPresetsApiView
        - [ ] SvQueryCategoryPresetsApiView
        - [ ] SvQueryInheritancePresetsApiView
    - [ ] `svs.serializers` - add serializers as needed for the AJAX/API end points
- [ ] Vue.js front-end
    - [ ] query form, modeled after variants vueapp
        - [ ] quick presets
        - [ ] footer
        - [ ] genotype tab
        - [ ] frequency
        - [ ] variants & effects
        - [ ] quality
        - [ ] gene lists & regions
        - [ ] regulatory elements
        - [ ] tads
    - [ ] results table
    - [ ] SV details
        - [ ] gene infos
        - [ ] regulatory elements
        - [ ] regulatory interactions
        - [ ] genotype & call infos
