### ISSUE TITLE
Allow users to store their own presets

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#776]
**Is your feature request related to a problem? Please describe.**
The currently available quick presets are useful. The main limitation is that users cannot adjust these settings.

**Describe the solution you'd like**
Add models, endpoints, and UI such that users can create their own presets. For now, it is sufficient to keep the presets in the categories frequency, impact, quality, chromosomes, and "flags etc.". Inheritance does not need to be configurable. Users should be able to adjust the entries in each category, starting out from the factory defaults.

The UI shall be implemented in Vue.js and thus this will be a bollonaster only feature.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by holtgrewe** [comment]
**Resolution Proposal**
We will need to implement new models, endpoints, and UI in the `variants` app. Integration into the variant filtration UI will be done by configuring the default presets for a project.

**Affected Components**
VarFish server

**Affected Modules/Files**
- `variants`

**Required Architectural Changes**
None

**Required Database Changes**
- Introduce models for representing the query presets.
- Introduce a new model for storing the default query presets per project.

**Backport Possible?**
No

**Implementation Plan**
- [ ] Add models for representing preset sets
- [ ] Add UI to create preset sets by copying from factory defaults or existing presets set
- [ ] Add UI for editing the preset sets
- [ ] Add model for storing default presets set for a project
- [ ] Add UI for displaying and showing the default presets set for project
